//Profile const
export const ADD_POST = 'ADD-POST'
export const UPDATE_NEW_POST_TEXT = 'UPDATE-NEW-POST-TEXT'
export const SET_USER_PROFILE = 'SET-USER-PROFILE'
export const TOGGLE_FETCHING_STATUS = 'TOGGLE-FETCHING-STATUS'
export const UPDATE_PROFILE = 'UPDATE-PROFILE'