//Profile const
export const SET_USER_PROFILE = 'PROFILE/SET-USER-PROFILE'
export const TOGGLE_FETCHING_STATUS = 'PROFILE/TOGGLE-FETCHING-STATUS'
export const ADD_POST = 'PROFILE/ADD-POST'
export const DELETE_POST = 'PROFILE/DELETE-POST'