//Users const
export const TOGGLE_FETCHING_STATUS = 'USERS/TOGGLE-FETCHING-STATUS'
export const SET_USERS = 'USERS/SET-USERS'
export const SET_TOTAL_PAGE = 'USERS/SET-TOTAL-PAGE'
export const SET_PAGES_COUNT = 'USERS/SET-PAGES-COUNT'
export const SET_PAGE_SIZE = 'USERS/SET-PAGE-SIZE'
export const TOGGLE_FOLLOW_TO_USER = 'USERS/TOGGLE-FOLLOW-TO-USER'
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USERS/TOGGLE-IS-FOLLOWING-PROGRESS'