//Users const
export const TOGGLE_FOLLOW_TO_USER = 'TOGGLE-FOLLOW-TO-USER'
export const TOGGLE_FETCHING_STATUS = 'TOGGLE-FETCHING-STATUS'
export const SET_USERS = 'SET-USERS'
export const SET_TOTAL_PAGE = 'SET-TOTAL-PAGE'
export const SET_PAGES_COUNT = 'SET-PAGES-COUNT'
export const SET_PAGE_SIZE = 'SET-PAGE-SIZE'